obsforgemonitor:

  database: '/lfs/h2/emc/obsproc/noscrub/edward.givelberg/orun/obsforge_task_monitor.db'
  data_root: "/lfs/h2/emc/da/noscrub/emc.da/obsForge/COMROOT/realtime"

  # Standalone only â€” omit in Rocoto mode
  time_range:
    start: "2025112000"
    end:   "2025112500"

  tasks:

    marinedump:
      run_type: gdas
      logfile_template: "logs/{date}{cycle}/gdas_marine_dump_prep.log"
      obs_path_template: "{run_type}.{date}/{cycle}/ocean"
      categories: auto

      # Explicitly name the categories to be monitored
      # categories:
        # sst: "sst"
        # icec: "icec"
        # sic: "sic"

