obsforgemonitor:

  database: '/lfs/h2/emc/obsproc/noscrub/edward.givelberg/orun/try/obsForge/parm/run/obsforge_task_monitor.db'
  data_root: "/lfs/h2/emc/obsproc/noscrub/edward.givelberg/orun/try/obsForge/parm/run/COMROOT/obsforge"

  # Standalone only â€” omit in Rocoto mode
  # time_range:
    # start: "2025112000"
    # end:   "2025112500"

  tasks:

    atmosbufrdump:
      run_type: gdas
      logfile_template: "logs/{date}{cycle}/gdas_atmos_bufr_dump_prep.log"
      obs_path_template: "{run_type}.{date}/{cycle}/atmos"
      categories:
        atmos: "atmos"

    aoddump:
      run_type: gdas
      logfile_template: "logs/{date}{cycle}/gdas_aod_dump_prep.log"
      obs_path_template: "{run_type}.{date}/{cycle}"
      categories:
        aod: "chem"

    marinedump:
      run_type: gdas
      logfile_template: "logs/{date}{cycle}/gdas_marine_dump_prep.log"
      obs_path_template: "{run_type}.{date}/{cycle}/ocean"
      # categories: auto

      # Explicitly name the categories to be monitored
      categories:
        adt: "adt"
        icec: "icec"
        sss: "sss"
        sst: "sst"

    marinebufrdump:
      run_type: gdas
      logfile_template: "logs/{date}{cycle}/gdas_marine_bufr_dump_prep.log"
      obs_path_template: "{run_type}.{date}/{cycle}/ocean"
      categories:
        insitu: "insitu"
